// THIS FILE IS AUTOGENERATED BY presamples SCRIPT
import "../../src/samples/test_sample.ts";
import "../../src/view/components/calculator/calc_sample.ts";



// TODO: require each 1 at a time and add file name

function clearSamples() {
  
}
