// THIS FILE IS AUTOGENERATED BY presamples SCRIPT
import { _addSampleFilename } from "./";
require("../../src/samples/test_sample.ts");
_addSampleFilename("../../src/samples/test_sample.ts");
require("../../src/view/components/calculator/calc_sample.ts");
_addSampleFilename("../../src/view/components/calculator/calc_sample.ts");
